# fly.toml app configuration file for staging environment
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deploy-test-damp-water-846-staging'
primary_region = 'lhr'

[build]

[env]
  DATABASE_URL = "/app/data/sqlite.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = "data"
  destination = "/app/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1