name: Deploy to Production

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    concurrency: deploy-production-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to production
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
